import Link from 'next/link'; import { ArrowRight, ArrowUpRight } from '@phosphor-icons/react/dist/ssr'; import { getProducts } from '@/lib/blogger'; import { HorizontalRail } from '@/components/HorizontalRail';
export default async function Home(){const products=await getProducts(); return <main>
<section className="hero"><div className="hero-media"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=2200&q=90" alt="Z-Clothes campaign"/></div><div className="hero-copy"><span className="eyebrow">PREMIUM CLOTHING FOR MODERN PEOPLE</span><h1>Wear<br/><em>Your Story.</em></h1><p>Discover premium quality clothing crafted for modern confidence, everyday movement and timeless style.</p><div className="hero-actions"><Link href="/products" className="btn light">Shop now <ArrowRight/></Link><Link href="/about" className="story-link">Watch our story <ArrowUpRight/></Link></div><div className="hero-stats"><span><b>10K+</b> Happy customers</span><span><b>500+</b> Products</span><span><b>4.8★</b> Average rating</span></div></div></section>
<section className="section featured"><div className="section-head"><div><span className="eyebrow dark">CURATED FOR YOU</span><h2>Featured Collections</h2></div><span className="scroll-hint">Scroll horizontally →</span></div><div className="category-rail">{['T-Shirts','Hoodies','Jackets','Cargo Pants','Shirts'].map((x,i)=><Link href={`/products?category=${encodeURIComponent(x)}`} className="category-card" key={x}><img src={products[i%products.length]?.image} alt=""/><div><b>{x}</b><span>Explore →</span></div></Link>)}</div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow dark">THE LATEST EDIT</span><h2>Featured Products</h2></div><Link href="/products" className="text-link">View all →</Link></div><HorizontalRail products={products.slice(0,8)}/></section>
<section className="season"><img src="https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=2200&q=90" alt="Season campaign"/><div><span className="eyebrow">LIMITED TIME</span><h2>Season Sale</h2><p>Selected styles, made for now.</p><Link href="/products" className="btn light">Shop the sale <ArrowRight/></Link></div></section>
<section className="trust-strip"><div>◈ <b>Free Shipping</b><span>On all orders</span></div><div>◇ <b>Secure Payment</b><span>Payments launching soon</span></div><div>○ <b>Easy Returns</b><span>Within 7 days</span></div><div>✦ <b>24/7 Support</b><span>We're here for you</span></div></section>
<section className="manifesto"><div className="manifesto-image"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1400&q=90" alt="Z-Clothes lifestyle"/></div><div className="manifesto-copy"><span className="eyebrow dark">OUR STORY</span><h2>Style for a better tomorrow.</h2><p>Z-Clothes is more than clothing brand—it’s a movement for people who express themselves through style. We make premium essentials that fit your journey, wherever it takes you.</p><Link href="/about" className="btn dark">Our journey <ArrowRight/></Link></div></section>
</main>}
